# Generated by Django 2.1 on 2018-08-17 12:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(default='500g', max_length=10)),
                ('images', models.CharField(max_length=100)),
                ('overview', tinymce.models.HTMLField()),
                ('descriptioin', models.CharField(max_length=500)),
                ('stock', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('hot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('class_name', models.CharField(max_length=10)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='df_goods.TypeInfo'),
        ),
    ]
