# Generated by Django 2.1 on 2018-08-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0002_auto_20180814_1154'),
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='df_goods.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='df_user.UserInfo')),
            ],
        ),
    ]
