# Generated by Django 2.1 on 2018-08-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('recipients', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('postcode', models.CharField(max_length=6)),
                ('mobilephone', models.CharField(max_length=11)),
            ],
        ),
    ]
